"""P0-4 测试：API 认证强制模式

原实现：PYCODER_API_KEY 未设置时不认证（开发友好但生产危险）。
现实现：未设置时自动生成临时 key，避免无意识暴露；
        显式设置 'disabled' 才完全关闭认证。
"""
from __future__ import annotations

import os
import sys
import importlib
import pytest
from fastapi.testclient import TestClient


def _reload_app_module():
    """重新加载 pycoder.server.app 模块以应用新的环境变量

    注意：`import pycoder.server.app as app_module` 在某些包结构下会被解析为
    FastAPI 实例（因包 __init__.py 的导出），因此使用 sys.modules 获取真正的模块。
    """
    # 清除已加载的模块缓存
    for mod_name in list(sys.modules.keys()):
        if mod_name == "pycoder.server.app" or mod_name.startswith("pycoder.server.app."):
            del sys.modules[mod_name]
    import pycoder.server.app  # 触发重新导入
    return sys.modules["pycoder.server.app"]


@pytest.fixture
def client_with_auth(monkeypatch):
    """配置了认证的测试客户端"""
    monkeypatch.setenv("PYCODER_API_KEY", "test-secret-key-12345")
    app_module = _reload_app_module()
    yield TestClient(app_module.app)
    # 清理：恢复无认证状态
    monkeypatch.setenv("PYCODER_API_KEY", "")
    _reload_app_module()


@pytest.fixture
def client_disabled(monkeypatch):
    """显式禁用认证的测试客户端"""
    monkeypatch.setenv("PYCODER_API_KEY", "disabled")
    app_module = _reload_app_module()
    yield TestClient(app_module.app)
    # 清理
    monkeypatch.setenv("PYCODER_API_KEY", "")
    _reload_app_module()


@pytest.fixture
def client_auto_generated(monkeypatch):
    """未设置环境变量时自动生成临时 key 的测试客户端"""
    monkeypatch.delenv("PYCODER_API_KEY", raising=False)
    app_module = _reload_app_module()
    # 保存自动生成的 key 用于测试
    auto_key = app_module._API_KEY
    yield TestClient(app_module.app), auto_key
    # 清理
    monkeypatch.setenv("PYCODER_API_KEY", "")
    _reload_app_module()


class TestAPIAuthEnforced:
    """认证模式：必须携带正确 X-API-Key"""

    def test_no_key_returns_401(self, client_with_auth):
        """未携带 X-API-Key 应返回 401"""
        resp = client_with_auth.get("/api/health")
        # /api/health 免认证
        assert resp.status_code == 200

        # 其他端点应 401（需携带 Origin 头，否则 file:// 免认证）
        resp = client_with_auth.get(
            "/api/config/keys",
            headers={"Origin": "http://localhost:5173"},
        )
        assert resp.status_code == 401

    def test_wrong_key_returns_401(self, client_with_auth):
        """错误的 X-API-Key 应返回 401"""
        resp = client_with_auth.get(
            "/api/config/keys",
            headers={
                "X-API-Key": "wrong-key",
                "Origin": "http://localhost:5173",
            },
        )
        assert resp.status_code == 401

    def test_correct_key_passes(self, client_with_auth):
        """正确的 X-API-Key 应通过认证"""
        resp = client_with_auth.get(
            "/api/config/keys",
            headers={
                "X-API-Key": "test-secret-key-12345",
                "Origin": "http://localhost:5173",
            },
        )
        # 不应是 401（其他状态码取决于端点是否存在/可用）
        assert resp.status_code != 401

    def test_health_endpoint_exempt(self, client_with_auth):
        """/api/health 应免认证"""
        resp = client_with_auth.get("/api/health")
        assert resp.status_code == 200

    def test_www_authenticate_header_present(self, client_with_auth):
        """401 响应应包含 WWW-Authenticate 头"""
        resp = client_with_auth.get(
            "/api/config/keys",
            headers={"Origin": "http://localhost:5173"},
        )
        assert resp.status_code == 401
        assert "WWW-Authenticate" in resp.headers
        assert "X-API-Key" in resp.headers["WWW-Authenticate"]


class TestDisabledMode:
    """显式 disabled 模式：完全关闭认证"""

    def test_disabled_mode_no_auth(self, client_disabled):
        """PYCODER_API_KEY=disabled 时不应返回 401"""
        resp = client_disabled.get(
            "/api/config/keys",
            headers={"Origin": "http://localhost:5173"},
        )
        assert resp.status_code != 401

    def test_health_endpoint_works(self, client_disabled):
        """/api/health 仍正常工作"""
        resp = client_disabled.get("/api/health")
        assert resp.status_code == 200


class TestAutoGeneratedKey:
    """未设置环境变量时自动生成临时 key"""

    def test_auto_generated_key_is_nonempty(self, client_auto_generated):
        """未设置环境变量时 _API_KEY 应为非空"""
        _, auto_key = client_auto_generated
        assert auto_key, "未设置 PYCODER_API_KEY 时应自动生成非空 key"
        assert len(auto_key) >= 20, "自动生成的 key 应有足够长度"

    def test_auto_generated_key_enforced(self, client_auto_generated):
        """自动生成的 key 应被强制用于认证"""
        client, auto_key = client_auto_generated

        # 无 key 应 401
        resp = client.get(
            "/api/config/keys",
            headers={"Origin": "http://localhost:5173"},
        )
        assert resp.status_code == 401

        # 错误 key 应 401
        resp = client.get(
            "/api/config/keys",
            headers={
                "X-API-Key": "wrong",
                "Origin": "http://localhost:5173",
            },
        )
        assert resp.status_code == 401

        # 正确 key 应通过
        resp = client.get(
            "/api/config/keys",
            headers={
                "X-API-Key": auto_key,
                "Origin": "http://localhost:5173",
            },
        )
        assert resp.status_code != 401


class TestTimingSafeComparison:
    """使用 secrets.compare_digest 防止时序攻击"""

    def test_compare_digest_used(self, monkeypatch):
        """验证 _secrets.compare_digest 被调用"""
        import pycoder.server.app as app_module

        # 验证模块使用 secrets.compare_digest
        assert hasattr(app_module, "_secrets")
        assert hasattr(app_module._secrets, "compare_digest")
