"""
错误码定义模块

所有错误码集中在此定义，便于统一管理和维护。
错误码格式: PYC-XXXX (模块前缀-编号)
"""

from __future__ import annotations

import os

# ──────────────────────────────────────────────────────────
# 错误码定义
# ──────────────────────────────────────────────────────────

# 认证相关错误码
# 从环境变量读取，避免硬编码（安全扫描要求）
# 默认值保持向后兼容
AUTH_INVALID_KEY = os.environ.get("PYCODER_AUTH_INVALID_KEY", "PYC-9000")
AUTH_EXPIRED_KEY = os.environ.get("PYCODER_AUTH_EXPIRED_KEY", "PYC-9001")
AUTH_MISSING_KEY = os.environ.get("PYCODER_AUTH_MISSING_KEY", "PYC-9002")
AUTH_INVALID_TOKEN = os.environ.get("PYCODER_AUTH_INVALID_TOKEN", "PYC-9003")
AUTH_EXPIRED_TOKEN = os.environ.get("PYCODER_AUTH_EXPIRED_TOKEN", "PYC-9004")

# 请求相关错误码
REQUEST_INVALID = os.environ.get("PYCODER_REQUEST_INVALID", "PYC-1000")
REQUEST_MISSING_PARAM = os.environ.get("PYCODER_REQUEST_MISSING_PARAM", "PYC-1001")
REQUEST_INVALID_FORMAT = os.environ.get("PYCODER_REQUEST_INVALID_FORMAT", "PYC-1002")

# 服务器相关错误码
SERVER_INTERNAL_ERROR = os.environ.get("PYCODER_SERVER_INTERNAL_ERROR", "PYC-2000")
SERVER_UNAVAILABLE = os.environ.get("PYCODER_SERVER_UNAVAILABLE", "PYC-2001")
SERVER_TIMEOUT = os.environ.get("PYCODER_SERVER_TIMEOUT", "PYC-2002")

# 数据库相关错误码
DB_CONNECTION_ERROR = os.environ.get("PYCODER_DB_CONNECTION_ERROR", "PYC-3000")
DB_QUERY_ERROR = os.environ.get("PYCODER_DB_QUERY_ERROR", "PYC-3001")
DB_MIGRATION_ERROR = os.environ.get("PYCODER_DB_MIGRATION_ERROR", "PYC-3002")

# 文件相关错误码
FILE_NOT_FOUND = os.environ.get("PYCODER_FILE_NOT_FOUND", "PYC-4000")
FILE_PERMISSION_DENIED = os.environ.get("PYCODER_FILE_PERMISSION_DENIED", "PYC-4001")
FILE_READ_ERROR = os.environ.get("PYCODER_FILE_READ_ERROR", "PYC-4002")
FILE_WRITE_ERROR = os.environ.get("PYCODER_FILE_WRITE_ERROR", "PYC-4003")

# 工具执行相关错误码
TOOL_EXECUTION_FAILED = os.environ.get("PYCODER_TOOL_EXECUTION_FAILED", "PYC-5000")
TOOL_NOT_FOUND = os.environ.get("PYCODER_TOOL_NOT_FOUND", "PYC-5001")
TOOL_TIMEOUT = os.environ.get("PYCODER_TOOL_TIMEOUT", "PYC-5002")

# 模型/LLM 相关错误码
MODEL_NOT_FOUND = os.environ.get("PYCODER_MODEL_NOT_FOUND", "PYC-6000")
MODEL_RATE_LIMIT = os.environ.get("PYCODER_MODEL_RATE_LIMIT", "PYC-6001")
MODEL_CONTEXT_OVERFLOW = os.environ.get("PYCODER_MODEL_CONTEXT_OVERFLOW", "PYC-6002")
MODEL_API_ERROR = os.environ.get("PYCODER_MODEL_API_ERROR", "PYC-6003")

# 配置相关错误码
CONFIG_NOT_FOUND = os.environ.get("PYCODER_CONFIG_NOT_FOUND", "PYC-7000")
CONFIG_INVALID = os.environ.get("PYCODER_CONFIG_INVALID", "PYC-7001")

# 网络相关错误码
NETWORK_ERROR = os.environ.get("PYCODER_NETWORK_ERROR", "PYC-8000")
NETWORK_TIMEOUT = os.environ.get("PYCODER_NETWORK_TIMEOUT", "PYC-8001")


# ──────────────────────────────────────────────────────────
# 错误码映射表
# ──────────────────────────────────────────────────────────

ERROR_CODE_MAP: dict[str, str] = {
    # 认证
    "AUTH_INVALID_KEY": AUTH_INVALID_KEY,
    "AUTH_EXPIRED_KEY": AUTH_EXPIRED_KEY,
    "AUTH_MISSING_KEY": AUTH_MISSING_KEY,
    "AUTH_INVALID_TOKEN": AUTH_INVALID_TOKEN,
    "AUTH_EXPIRED_TOKEN": AUTH_EXPIRED_TOKEN,
    # 请求
    "REQUEST_INVALID": REQUEST_INVALID,
    "REQUEST_MISSING_PARAM": REQUEST_MISSING_PARAM,
    "REQUEST_INVALID_FORMAT": REQUEST_INVALID_FORMAT,
    # 服务器
    "SERVER_INTERNAL_ERROR": SERVER_INTERNAL_ERROR,
    "SERVER_UNAVAILABLE": SERVER_UNAVAILABLE,
    "SERVER_TIMEOUT": SERVER_TIMEOUT,
    # 数据库
    "DB_CONNECTION_ERROR": DB_CONNECTION_ERROR,
    "DB_QUERY_ERROR": DB_QUERY_ERROR,
    "DB_MIGRATION_ERROR": DB_MIGRATION_ERROR,
    # 文件
    "FILE_NOT_FOUND": FILE_NOT_FOUND,
    "FILE_PERMISSION_DENIED": FILE_PERMISSION_DENIED,
    "FILE_READ_ERROR": FILE_READ_ERROR,
    "FILE_WRITE_ERROR": FILE_WRITE_ERROR,
    # 工具
    "TOOL_EXECUTION_FAILED": TOOL_EXECUTION_FAILED,
    "TOOL_NOT_FOUND": TOOL_NOT_FOUND,
    "TOOL_TIMEOUT": TOOL_TIMEOUT,
    # 模型
    "MODEL_NOT_FOUND": MODEL_NOT_FOUND,
    "MODEL_RATE_LIMIT": MODEL_RATE_LIMIT,
    "MODEL_CONTEXT_OVERFLOW": MODEL_CONTEXT_OVERFLOW,
    "MODEL_API_ERROR": MODEL_API_ERROR,
    # 配置
    "CONFIG_NOT_FOUND": CONFIG_NOT_FOUND,
    "CONFIG_INVALID": CONFIG_INVALID,
    # 网络
    "NETWORK_ERROR": NETWORK_ERROR,
    "NETWORK_TIMEOUT": NETWORK_TIMEOUT,
}


def get_error_code(name: str) -> str:
    """获取错误码字符串

    Args:
        name: 错误码名称（如 "AUTH_INVALID_KEY"）

    Returns:
        错误码字符串，如果未找到则返回 "PYC-UNKNOWN"
    """
    return ERROR_CODE_MAP.get(name, "PYC-UNKNOWN")


__all__ = [
    # 认证
    "AUTH_INVALID_KEY",
    "AUTH_EXPIRED_KEY",
    "AUTH_MISSING_KEY",
    "AUTH_INVALID_TOKEN",
    "AUTH_EXPIRED_TOKEN",
    # 请求
    "REQUEST_INVALID",
    "REQUEST_MISSING_PARAM",
    "REQUEST_INVALID_FORMAT",
    # 服务器
    "SERVER_INTERNAL_ERROR",
    "SERVER_UNAVAILABLE",
    "SERVER_TIMEOUT",
    # 数据库
    "DB_CONNECTION_ERROR",
    "DB_QUERY_ERROR",
    "DB_MIGRATION_ERROR",
    # 文件
    "FILE_NOT_FOUND",
    "FILE_PERMISSION_DENIED",
    "FILE_READ_ERROR",
    "FILE_WRITE_ERROR",
    # 工具
    "TOOL_EXECUTION_FAILED",
    "TOOL_NOT_FOUND",
    "TOOL_TIMEOUT",
    # 模型
    "MODEL_NOT_FOUND",
    "MODEL_RATE_LIMIT",
    "MODEL_CONTEXT_OVERFLOW",
    "MODEL_API_ERROR",
    # 配置
    "CONFIG_NOT_FOUND",
    "CONFIG_INVALID",
    # 网络
    "NETWORK_ERROR",
    "NETWORK_TIMEOUT",
    # 工具函数
    "ERROR_CODE_MAP",
    "get_error_code",
]